#Requires -Version 5.1
<#
.SYNOPSIS
  EISA Homelab Ultimate first-run / reconfigure wizard.

.DESCRIPTION
  Walks the user through configuring .env, rendering the Caddyfile,
  Authelia configuration.yml, and SearXNG settings.yml from their
  .tmpl templates, generating fresh secrets where required, and
  finally invoking `docker compose up -d` (with the `tunnel` profile
  when the user chose Cloudflare tunnel mode).

.PARAMETER Reconfigure
  Re-prompt every value even if .env already has it set. Without this
  flag the wizard only fills in missing / placeholder values, then
  re-renders templates if .env has changed.

.PARAMETER NoStart
  Run the wizard and stop. Useful for prepping a clean checkout.
#>

[CmdletBinding()]
param(
    [switch]$Reconfigure,
    [switch]$NoStart
)

# --- locate project root (one level up from this script) -----------------
$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

$EnvFile     = Join-Path $ProjectRoot '.env'
$EnvExample  = Join-Path $ProjectRoot '.env.example'
$ComposeFile = Join-Path $ProjectRoot 'docker-compose.yml'

# --- pretty printing helpers --------------------------------------------
function Write-Banner {
    param([string]$Text)
    $line = '=' * 72
    Write-Host ''
    Write-Host $line -ForegroundColor Cyan
    Write-Host "  $Text" -ForegroundColor Cyan
    Write-Host $line -ForegroundColor Cyan
}

function Write-Step  { param([string]$T) Write-Host ''; Write-Host ">>> $T" -ForegroundColor Yellow }
function Write-Info  { param([string]$T) Write-Host "    $T" -ForegroundColor Gray  }
function Write-Ok    { param([string]$T) Write-Host "    [OK] $T" -ForegroundColor Green }
function Write-Warn2 { param([string]$T) Write-Host "    [!]  $T" -ForegroundColor Yellow }
function Write-Err   { param([string]$T) Write-Host "    [X]  $T" -ForegroundColor Red }

# --- preflight: docker ---------------------------------------------------
function Test-Docker {
    Write-Step 'Checking Docker'
    try {
        $v = (& docker --version) 2>&1
        if ($LASTEXITCODE -ne 0) { throw $v }
        Write-Ok $v
    } catch {
        Write-Err 'docker CLI not found. Install Docker Desktop and re-run.'
        Write-Info 'https://docs.docker.com/desktop/install/windows-install/'
        exit 1
    }
    try {
        $null = (& docker info --format '{{.ServerVersion}}') 2>&1
        if ($LASTEXITCODE -ne 0) { throw 'engine not responding' }
        Write-Ok 'Docker engine is running.'
    } catch {
        Write-Err 'Docker engine is not running. Start Docker Desktop and re-run.'
        exit 1
    }
}

# --- env file as ordered hashtable --------------------------------------
function Read-EnvFile {
    param([string]$Path)
    $map = [ordered]@{}
    if (-not (Test-Path $Path)) { return $map }
    foreach ($line in Get-Content $Path) {
        if ($line -match '^\s*#' -or $line -match '^\s*$') { continue }
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$') {
            $map[$Matches[1]] = $Matches[2]
        }
    }
    return $map
}

function Write-EnvFile {
    param([string]$Path, $Map)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Generated by setup.ps1 — re-run RUN.bat --reconfigure to change values.')
    [void]$sb.AppendLine('# Sensitive: never commit this file (it is gitignored).')
    foreach ($k in $Map.Keys) {
        [void]$sb.AppendLine("$k=$($Map[$k])")
    }
    Set-Content -Path $Path -Value $sb.ToString() -Encoding ASCII
}

# --- secret generation --------------------------------------------------
function New-HexSecret {
    param([int]$Bytes = 32)
    $b = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    -join ($b | ForEach-Object { $_.ToString('x2') })
}

function New-Base64Secret {
    param([int]$Bytes = 32)
    $b = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    [Convert]::ToBase64String($b)
}

# --- prompts ------------------------------------------------------------
function Ask {
    param(
        [string]$Prompt,
        [string]$Default = '',
        [switch]$Secret,
        [switch]$AllowEmpty
    )
    while ($true) {
        $hint = if ($Default) { " [$Default]" } else { '' }
        if ($Secret) {
            $sec = Read-Host -Prompt "$Prompt$hint" -AsSecureString
            $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
            $val  = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
            [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        } else {
            $val = Read-Host -Prompt "$Prompt$hint"
        }
        if ([string]::IsNullOrWhiteSpace($val)) { $val = $Default }
        if ([string]::IsNullOrWhiteSpace($val) -and -not $AllowEmpty) {
            Write-Warn2 'Value is required.'
            continue
        }
        return $val
    }
}

function Ask-YesNo {
    param([string]$Prompt, [bool]$DefaultYes = $true)
    $def = if ($DefaultYes) { 'Y/n' } else { 'y/N' }
    while ($true) {
        $a = (Read-Host "$Prompt [$def]").Trim().ToLower()
        if ([string]::IsNullOrEmpty($a)) { return $DefaultYes }
        switch ($a) {
            'y' { return $true }
            'yes' { return $true }
            'n' { return $false }
            'no' { return $false }
            default { Write-Warn2 'Please answer y or n.' }
        }
    }
}

# --- detect placeholder values -----------------------------------------
function Test-Placeholder {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return $true }
    return $Value -match '^__.*__$' -or $Value -match 'CHANGE_ME' -or $Value -match 'GENERATE_'
}

# --- main wizard --------------------------------------------------------
function Invoke-Wizard {
    Write-Banner 'EISA HOMELAB ULTIMATE — first-run wizard'

    # Bootstrap .env from .env.example if missing.
    if (-not (Test-Path $EnvFile)) {
        Write-Step 'No .env found — bootstrapping from .env.example'
        Copy-Item $EnvExample $EnvFile
        Write-Ok 'Created .env'
    }

    $envMap     = Read-EnvFile $EnvFile
    $exampleMap = Read-EnvFile $EnvExample

    # Make sure every key from .env.example exists in .env.
    foreach ($k in $exampleMap.Keys) {
        if (-not $envMap.Contains($k)) { $envMap[$k] = $exampleMap[$k] }
    }

    # ---- access mode ---------------------------------------------------
    Write-Step 'Access mode'
    Write-Info 'LOCAL-ONLY:    services reachable only on this LAN by host:port.'
    Write-Info 'TUNNEL:        Cloudflare tunnel publishes services on subdomains'
    Write-Info '               of a domain you own (e.g. chat.example.com).'
    $useTunnel = Ask-YesNo 'Enable Cloudflare tunnel (online access via your domain)?' $false

    if ($useTunnel) {
        $needDomain = $Reconfigure -or [string]::IsNullOrWhiteSpace($envMap['DOMAIN'])
        if ($needDomain) {
            $envMap['DOMAIN'] = Ask 'Your domain (e.g. example.com)' $envMap['DOMAIN']
        }
        $needToken = $Reconfigure -or (Test-Placeholder $envMap['CLOUDFLARE_TUNNEL_TOKEN'])
        if ($needToken) {
            Write-Info 'Get your tunnel token at: https://one.dash.cloudflare.com/'
            Write-Info '  -> Networks -> Tunnels -> Create -> "Install connector" panel'
            $envMap['CLOUDFLARE_TUNNEL_TOKEN'] = Ask 'Cloudflare tunnel token' $envMap['CLOUDFLARE_TUNNEL_TOKEN'] -Secret
        }
    } else {
        $envMap['DOMAIN'] = ''
        $envMap['CLOUDFLARE_TUNNEL_TOKEN'] = ''
        Write-Ok 'Local-only mode selected (no tunnel).'
    }

    # ---- storage paths -------------------------------------------------
    Write-Step 'Storage paths'
    Write-Info 'STORAGE_DISK = drive root holding your media (e.g. F: on Windows).'
    if ($Reconfigure -or (Test-Placeholder $envMap['STORAGE_DISK'])) {
        $envMap['STORAGE_DISK'] = Ask 'Storage disk root' $envMap['STORAGE_DISK']
    }
    if ($Reconfigure -or (Test-Placeholder $envMap['PERSISTENT_STORAGE'])) {
        $envMap['PERSISTENT_STORAGE'] = Ask 'Persistent-storage path (configs/databases)' $envMap['PERSISTENT_STORAGE']
    }

    $mediaKeys = @(
        'DOWNLOADS_LOCATION','SOFTWARE_LOCATION','GAMES_LOCATION',
        'VIDEOS_LOCATION','AUDIO_LOCATION','PICTURES_LOCATION',
        'DOCUMENTS_LOCATION','PLEX_LOCATION','BOOKS_LOCATION'
    )
    if ($Reconfigure -or (Ask-YesNo 'Customize individual media folder paths?' $false)) {
        foreach ($k in $mediaKeys) {
            $envMap[$k] = Ask "  $k (relative to $($envMap['STORAGE_DISK']))" $envMap[$k]
        }
    } else {
        Write-Ok 'Keeping default media folder layout.'
    }

    # ---- generated secrets --------------------------------------------
    Write-Step 'Generating secrets where missing'
    $genSpecs = @(
        @{ Key='POSTGRES_PASSWORD';                Bytes=24; Mode='hex' },
        @{ Key='N8N_ENCRYPTION_KEY';               Bytes=32; Mode='hex' },
        @{ Key='N8N_USER_MANAGEMENT_JWT_SECRET';   Bytes=32; Mode='hex' },
        @{ Key='HERMES_API_KEY';                   Bytes=32; Mode='hex' },
        @{ Key='HERMES_DASHBOARD_TOKEN';           Bytes=32; Mode='hex' },
        @{ Key='NEXTAUTH_SECRET';                  Bytes=32; Mode='b64' },
        @{ Key='LINKWARDEN_DB_PASSWORD';           Bytes=20; Mode='hex' },
        @{ Key='DB_PASSWORD';                      Bytes=20; Mode='hex' },
        # Tor browser (KasmVNC) — never seen by the user, only baked into
        # the auto-login URL Caddy redirects to and the container's VNC_PW.
        @{ Key='TOR_VNC_PW';                       Bytes=12; Mode='hex' }
    )
    foreach ($s in $genSpecs) {
        if ($Reconfigure -or (Test-Placeholder $envMap[$s.Key])) {
            $envMap[$s.Key] = if ($s.Mode -eq 'hex') { New-HexSecret -Bytes $s.Bytes } else { New-Base64Secret -Bytes $s.Bytes }
            Write-Ok "Generated $($s.Key)"
        }
    }

    # ---- user-facing passwords ----------------------------------------
    if ($Reconfigure -or (Test-Placeholder $envMap['HERMES_WORKSPACE_PASSWORD'])) {
        Write-Step 'Hermes workspace password'
        $envMap['HERMES_WORKSPACE_PASSWORD'] = Ask 'Set workspace UI password' '' -Secret
    }

    # ---- write .env back ----------------------------------------------
    Write-EnvFile $EnvFile $envMap
    Write-Ok ".env written ($EnvFile)"

    return @{ Env = $envMap; UseTunnel = $useTunnel }
}

# --- template rendering -------------------------------------------------
function Resolve-Template {
    param([string]$TemplatePath, [string]$OutputPath, $Env)
    if (-not (Test-Path $TemplatePath)) {
        Write-Warn2 "Template missing: $TemplatePath (skipping)"
        return
    }
    $text = Get-Content $TemplatePath -Raw
    # Direct token replacements (literal string .Replace — no regex surprises).
    $text = $text.Replace('__SEARXNG_SECRET_KEY__',              [string]$Env['SEARXNG_SECRET_KEY'])
    $text = $text.Replace('__AUTHELIA_JWT_SECRET__',             [string]$Env['AUTHELIA_JWT_SECRET'])
    $text = $text.Replace('__AUTHELIA_STORAGE_ENCRYPTION_KEY__', [string]$Env['AUTHELIA_STORAGE_ENCRYPTION_KEY'])
    foreach ($k in $Env.Keys) {
        $needle = '${' + $k + '}'
        $text = $text.Replace($needle, [string]$Env[$k])
    }
    Set-Content -Path $OutputPath -Value $text -Encoding UTF8
    Write-Ok "Rendered $OutputPath"
}

function Write-LocalOnlyCaddyfile {
    param([string]$OutputPath, $Env)
    $torPw   = [string]$Env['TOR_VNC_PW']
    $torAuth = [string]$Env['TOR_BASIC_AUTH']
    $content = @"
# =============================================================================
# Caddy reverse proxy — LOCAL-ONLY MODE
# DOMAIN was left empty in .env, so no public *.${DOMAIN} hosts are
# rendered. Direct service URLs (still work):
#
#   http://localhost:8080   Heimdall (start page)
#   http://localhost:9091   Authelia (only useful in tunnel mode)
#   http://localhost:9014   Jellyfin
#   http://localhost:4533   Navidrome
#   http://localhost:8095   Filebrowser
#   http://localhost:9002   Open WebUI
#   http://localhost:11434  Ollama
#   http://localhost:8031   SearXNG
#   http://localhost:5678   n8n
#   http://localhost:9000   Portainer
#
# Special: http://tor.localhost/  --  zero-click Tor browser (no kasm prompt).
# *.localhost resolves to 127.0.0.1 automatically on Windows 10+, macOS, Linux.
# =============================================================================

{
    auto_https off
    http_port 80
}

http://tor.localhost {
    @root path /
    redir @root /vnc.html?username=kasm_user&password=$torPw&autoconnect=true&resize=remote 302
    reverse_proxy https://host.docker.internal:6901 {
        transport http {
            tls_insecure_skip_verify
        }
        header_up Authorization "Basic $torAuth"
    }
}

:80 {
    respond "EISA Homelab - local-only mode. Open http://tor.localhost/ for the Tor browser; see Caddyfile for other services." 200
}
"@
    Set-Content -Path $OutputPath -Value $content -Encoding UTF8
    Write-Ok "Wrote local-only Caddyfile -> $OutputPath"
}

function Render-Templates {
    param($Env)
    Write-Step 'Rendering config templates'

    # Generate Caddy/Authelia/SearXNG-only secrets that don't live in .env.
    $stateFile = Join-Path $ProjectRoot '.wizard-state.json'
    $state = if (Test-Path $stateFile) {
        Get-Content $stateFile -Raw | ConvertFrom-Json
    } else {
        [pscustomobject]@{ SEARXNG_SECRET_KEY=''; AUTHELIA_JWT_SECRET=''; AUTHELIA_STORAGE_ENCRYPTION_KEY='' }
    }
    if ([string]::IsNullOrWhiteSpace($state.SEARXNG_SECRET_KEY))            { $state.SEARXNG_SECRET_KEY            = New-HexSecret 32 }
    if ([string]::IsNullOrWhiteSpace($state.AUTHELIA_JWT_SECRET))           { $state.AUTHELIA_JWT_SECRET           = New-HexSecret 32 }
    if ([string]::IsNullOrWhiteSpace($state.AUTHELIA_STORAGE_ENCRYPTION_KEY)){ $state.AUTHELIA_STORAGE_ENCRYPTION_KEY = New-HexSecret 32 }
    $state | ConvertTo-Json | Set-Content $stateFile -Encoding ASCII

    $renderEnv = [ordered]@{}
    foreach ($k in $Env.Keys) { $renderEnv[$k] = $Env[$k] }
    $renderEnv['SEARXNG_SECRET_KEY']             = $state.SEARXNG_SECRET_KEY
    $renderEnv['AUTHELIA_JWT_SECRET']            = $state.AUTHELIA_JWT_SECRET
    $renderEnv['AUTHELIA_STORAGE_ENCRYPTION_KEY']= $state.AUTHELIA_STORAGE_ENCRYPTION_KEY
    # Pre-compute the kasm basic-auth header value so the Caddy redirect
    # for tor.${DOMAIN} can inject Authorization on proxied requests
    # (kasm's /vnc.html is HTTP-basic-auth gated).
    $torCred = "kasm_user:" + [string]$Env['TOR_VNC_PW']
    $renderEnv['TOR_BASIC_AUTH'] = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($torCred))

    if ([string]::IsNullOrWhiteSpace($Env['DOMAIN'])) {
        Write-LocalOnlyCaddyfile -OutputPath (Join-Path $ProjectRoot 'persistent-storage\caddy\Caddyfile') -Env $renderEnv
    } else {
        Resolve-Template `
            (Join-Path $ProjectRoot 'persistent-storage\caddy\Caddyfile.tmpl') `
            (Join-Path $ProjectRoot 'persistent-storage\caddy\Caddyfile') `
            $renderEnv
    }
    # Authelia config still gets rendered — even in local-only mode it's
    # mounted by compose. ${DOMAIN} just becomes empty (Authelia won't
    # actively guard anything since Caddy isn't forwarding to it).
    Resolve-Template `
        (Join-Path $ProjectRoot 'persistent-storage\authelia\configuration.yml.tmpl') `
        (Join-Path $ProjectRoot 'persistent-storage\authelia\configuration.yml') `
        $renderEnv
    Resolve-Template `
        (Join-Path $ProjectRoot 'persistent-storage\do-not-delete\searxng\settings.yml.tmpl') `
        (Join-Path $ProjectRoot 'persistent-storage\do-not-delete\searxng\settings.yml') `
        $renderEnv

    # users_database.yml.example -> users_database.yml only if missing.
    $usersExample = Join-Path $ProjectRoot 'persistent-storage\authelia\users_database.yml.example'
    $usersFile    = Join-Path $ProjectRoot 'persistent-storage\authelia\users_database.yml'
    if (-not (Test-Path $usersFile)) {
        Copy-Item $usersExample $usersFile
        Write-Warn2 "Copied users_database.yml from template — you MUST edit it and replace"
        Write-Warn2 "the password hash before Authelia will start. Generate one with:"
        Write-Warn2 "  docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password 'YOUR_PASSWORD'"
    }
}

# --- compose up ---------------------------------------------------------
function Start-Stack {
    param([bool]$UseTunnel)
    Write-Step 'Starting docker compose stack'
    $args = @('compose','up','-d')
    if ($UseTunnel) {
        Write-Info 'Including tunnel profile (cloudflared).'
        $args = @('compose','--profile','tunnel') + @('up','-d')
    }
    & docker @args
    if ($LASTEXITCODE -ne 0) {
        Write-Err 'docker compose up failed.'
        exit $LASTEXITCODE
    }
    Write-Ok 'Stack is up.'
}

# --- summary ------------------------------------------------------------
function Show-Summary {
    param($Env, [bool]$UseTunnel)
    Write-Banner 'Done — service map'
    if ($UseTunnel -and $Env['DOMAIN']) {
        $d = $Env['DOMAIN']
        Write-Info "Public (via Cloudflare tunnel + Authelia SSO):"
        Write-Info "  hub.$d, chat.$d, music.$d, movie.$d, file.$d, n8n.$d, search.$d, ..."
    }
    Write-Info ''
    Write-Info 'Local (LAN):'
    Write-Info '  Heimdall   http://localhost:8080'
    Write-Info '  Authelia   http://localhost:9091'
    Write-Info '  Jellyfin   http://localhost:9014'
    Write-Info '  Navidrome  http://localhost:4533'
    Write-Info '  Filebrowser http://localhost:8095'
    Write-Info '  Open WebUI http://localhost:9002'
    Write-Info '  Ollama API http://localhost:11434'
    Write-Info '  SearXNG    http://localhost:8031'
    Write-Info '  n8n        http://localhost:5678'
    Write-Info '  Portainer  http://localhost:9000'
    Write-Info '  Tor Browser (zero-click auto-login):'
    Write-Info '    http://tor.localhost/'
}

# --- run ---------------------------------------------------------------
Test-Docker
$result = Invoke-Wizard
Render-Templates -Env $result.Env
if (-not $NoStart) {
    Start-Stack -UseTunnel $result.UseTunnel
}
Show-Summary -Env $result.Env -UseTunnel $result.UseTunnel
